languageCode = "rs"
theme = "ananke"
baseURL = "https://smartinov.github.io/wedding"
title = "Stefan & Darija"


MetaDataFormat = "yaml"
DefaultContentLanguage = "rs"
SectionPagesMenu = "main"
Paginate = 15 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "The last theme you'll ever need. Maybe."
  facebook = ""
  # twitter = "https://twitter.com/GoHugoIO"
  instagram = ""
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-white"
  featured_image = "/images/background.jpg"
  recent_posts_number = 2
  custom_css = ["/css/custom.css"]


[languages]
    [languages.rs]
        title = "Stefan & Darija"
        languageName = "English"
    [languages.en]
        title = "Stefan i Darija"
        languageName = "Srpski"