languageCode = "rs"
theme = "ananke"
baseURL = "https://darijaistefan.wedding"
title = "Darija i Stefan"

MetaDataFormat = "yaml"
DefaultContentLanguage = "rs"
SectionPagesMenu = "main"
Paginate = 15 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = "UA-171243407-1"
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "The last theme you'll ever need. Maybe."
  facebook = ""
  # twitter = "https://twitter.com/GoHugoIO"
  instagram = ""
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-white"
  featured_image = "/images/background.jpg"
  recent_posts_number = 5
  custom_css = ["/css/custom.css"]
  googleMapsAPIKey = "AIzaSyCMUtavmNINk7UqJN5UeWAjUuSPmDGTR00"